// IMAGINE A SITUATION WHERE YOU HAVE 1000 KEYS WITH VALUES FROM (0 TO 999), HOW WOULD YOU IMPLEMENT FOLLOWING IN 0(1) TIMES 

// SEARCH 
//INSERT
//DELETE 


// it doesn't handle large value 
// it doesn't handle floating no 
// it doesn't handle string which is combination of digits and charcters

#include<iostream>
using namespace std;
int main(){
    int n;
    cin>>n;
    bool arr[10]=0;
    for(int i=0;i<n;i++){
        
    }
    return 0;
}
